"""Streamlit demo — natural language search over MovieLens indexes."""

from __future__ import annotations

import json

import pandas as pd
import streamlit as st

from src.ai.generator import execute_query, generate_query
from src.ai.ollama_client import OllamaError, chat
from src.ai.parser import ParseError
from src.ai.validator import ValidationError

EXAMPLE_QUESTIONS = [
    "Show Comedy movies released after 2000.",
    "What are the 10 highest-rated Comedy movies with at least 100 ratings?",
    "Which genres have the highest average rating? (top 10 genres)",
    "What were the 10 most popular movies by rating activity in 2010?",
    "Which release years have the highest total rating count? (top 10)",
]

PAGE_TITLE = "MovieLens Smart Analytics"


def _hits_to_records(response: dict) -> list[dict]:
    return [hit.get("_source", {}) for hit in response.get("hits", {}).get("hits", [])]


def _summarize_for_explanation(result: dict, limit: int = 5) -> str:
    records = _hits_to_records(result)
    if records:
        return json.dumps(records[:limit], ensure_ascii=False, default=str)
    aggregations = result.get("aggregations")
    if aggregations:
        return json.dumps(aggregations, ensure_ascii=False, default=str)[:3000]
    return "No documents or aggregations returned."


def _generate_explanation(
    question: str,
    index: str,
    hits: int,
    agg_buckets: int,
    result: dict,
) -> str:
    sample = _summarize_for_explanation(result)
    user_message = (
        f"Question: {question}\n"
        f"Index: {index}\n"
        f"Matching documents: {hits}\n"
        f"Aggregation buckets: {agg_buckets}\n"
        f"Sample results:\n{sample}\n\n"
        "Write 2–3 sentences summarizing what the results show. "
        "Do not invent movies or numbers not present in the sample."
    )
    return chat(
        "You summarize Elasticsearch search results in plain English for end users.",
        user_message,
        json_format=False,
    )


def _render_results(result: dict) -> None:
    hits = result.get("hits", {}).get("hits", [])
    aggregations = result.get("aggregations")

    if hits:
        records = _hits_to_records(result)
        st.subheader("Results")
        st.caption(f"{len(records)} document(s) shown (page size from query)")
        st.dataframe(pd.DataFrame(records), use_container_width=True)

    if aggregations:
        st.subheader("Aggregations")
        st.json(aggregations)

    if not hits and not aggregations:
        st.info("Query ran successfully but returned no documents or aggregations.")


def main() -> None:
    st.set_page_config(page_title=PAGE_TITLE, page_icon="🎬", layout="wide")
    st.title(PAGE_TITLE)
    st.caption(
        "Ask questions in plain English. The app uses Ollama to build an Elasticsearch "
        "query, validates it, then runs it against your loaded MovieLens indexes."
    )

    with st.sidebar:
        st.header("Examples")
        for example in EXAMPLE_QUESTIONS:
            if st.button(example, use_container_width=True, key=f"example::{example}"):
                st.session_state["question"] = example
        st.divider()
        show_explanation = st.checkbox("Show AI summary of results", value=False)
        st.caption("Summary is generated by the LLM and may be imperfect.")

    question = st.text_area(
        "Ask a question about MovieLens:",
        value=st.session_state.get("question", ""),
        height=100,
        placeholder="Which Comedy movies have the highest average rating?",
    )
    search = st.button("Search", type="primary")

    if not search:
        return

    if not question.strip():
        st.warning("Enter a question first.")
        return

    st.session_state["question"] = question

    try:
        with st.spinner("Generating Elasticsearch query with Ollama…"):
            generated = generate_query(question)
    except (OllamaError, ParseError, ValidationError, ValueError) as exc:
        st.error(f"Could not generate a valid query: {exc}")
        return

    st.subheader("Generated query")
    col_index, col_stats = st.columns(2)
    col_index.metric("Index", generated.index)
    col_stats.metric("Validated", "Yes")

    st.code(
        json.dumps({"index": generated.index, "body": generated.body}, indent=2),
        language="json",
    )

    try:
        with st.spinner("Running validated query against Elasticsearch…"):
            exec_result = execute_query(generated)
    except Exception as exc:
        st.error(f"Elasticsearch error: {exc}")
        return

    st.metric("Total matching documents", f"{exec_result.hits:,}")
    if exec_result.agg_buckets:
        st.metric("Aggregation buckets", exec_result.agg_buckets)

    _render_results(exec_result.response)

    if show_explanation:
        try:
            with st.spinner("Generating AI summary…"):
                explanation = _generate_explanation(
                    question,
                    generated.index,
                    exec_result.hits,
                    exec_result.agg_buckets,
                    exec_result.response,
                )
            st.subheader("AI summary")
            st.info(explanation)
            st.caption("This summary is LLM-generated from the result sample above.")
        except OllamaError as exc:
            st.warning(f"Could not generate summary: {exc}")


if __name__ == "__main__":
    main()
